<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2685.6">
  <style type="text/css">
    body {background-color: #eaeee5}
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 26.0px 'Helvetica Neue'; color: #122822; -webkit-text-stroke: #122822}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #1b3a32; -webkit-text-stroke: #1b3a32}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 16.0px 'Helvetica Neue'; color: #1b3a32; -webkit-text-stroke: #1b3a32}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; font: 15.0px 'Helvetica Neue'; color: #16211d; -webkit-text-stroke: #16211d; background-color: #ffffff; min-height: 18.0px}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; text-align: center; font: 14.0px 'Helvetica Neue'; color: #eaeee5; -webkit-text-stroke: #eaeee5; background-color: #122822}
    p.p6 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; color: #934f22; -webkit-text-stroke: #934f22}
    p.p7 {margin: 0.0px 0.0px 0.0px 0.0px; font: 11.0px 'Helvetica Neue'; color: #787f73; -webkit-text-stroke: #787f73}
    span.s1 {font-kerning: none}
    span.s2 {font-kerning: none; color: #934f22; -webkit-text-stroke: 0px #934f22}
    span.s3 {font-kerning: none; color: #1b3a32; -webkit-text-stroke: 0px #1b3a32}
    span.s4 {text-decoration: underline ; font-kerning: none}
  </style>
</head>
<body>
<p class="p1"><span class="s1">vet</span><span class="s2">look</span><span class="s1">up</span></p>
<p class="p2"><span class="s1">BETA</span></p>
<p class="p3"><span class="s1">"What's actually in this medicine my pet was given?"</span></p>
<p class="p4"><span class="s1"></span><br></p>
<p class="p5"><span class="s1">Look up</span></p>
<p class="p6"><span class="s3">Try: </span><span class="s4">Rimadyl</span><span class="s3"> · </span><span class="s4">Apoquel</span><span class="s3"> · </span><span class="s4">Cerenia</span></p>
<p class="p7"><span class="s1">Vetlookup results are generated by AI and may be incomplete or wrong — always verify with a licensed veterinarian, especially before giving any human medication to a pet. Never substitute medications without professional guidance.</span></p>
</body>
</html>
